#!/bin/sh

echo "Stopping services..."
service astrobox stop

echo "Removing generated AstroBox files..."
rm /etc/astrobox/config.yaml
rm /etc/astrobox/box-id
rm /etc/astrobox/default-hostname
rm /var/log/astrobox/*

echo "Removing generated system files..."
rm /etc/udev/rules.d/70-persistent-net.rules

echo "Emptying data directory"
rm -r /AstroBoxFiles

echo "Removing command history"
history -c

echo "***********************************************"
echo "* Your SD Card is clean and ready for imaging *"
echo "*                                             *"
echo "* Shutdown your RPi and se your Mac to create *"
echo "* an image of it.                             *"
echo "***********************************************"
